---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
